### ISSUE TITLE
DS18B20 wrong wiring 

### ISSUE THREAD

**Issue by energiebrand** [fehlfarbe/arduino-motorfocus#9]
Hi Marcus,
build your motor-focusser last year and still in operation with Astroberry / INDI on my Newton. We had some discussion about the problem with ASCOM...
Now I developed some new 3D parts for a SVBony APO since the buttons on the 1:10 gear are bigger than yours.
However first time I added an 18B20 and burned my fingers... the wiring on your diagram is wrong. + and - are inverted.

**Comment by fehlfarbe** [comment]
You are right! I think the DS18B20 part in Fritzing is wrong because it says VDD | DATA | GND:

![Untitled](https://user-images.githubusercontent.com/3355380/144331457-98be5755-04e6-486d-a2b8-b52ceb48df90.png)

But data sheet says it's GND | DATA | VDD https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf

The broken Fritzing part might be the reason why I burned my fingers several times on the temperature sensor too :laughing:
